### ISSUE TITLE
Tag new release for pypcap

### ISSUE THREAD

**Issue by hellais** [pynetwork/pypcap#37]
There are numerous important fixes added to pypcap since the 1.1.5 release.

I think we should do a long awaited new release, should we even be so ambitious to call it 1.2?

This is also a good chance to clean up the pending PRs and merge them into master before the release.

Here is what needs to happen:

Merge pending PRs:

* [x] Add travis CI integration (#25)
* [x] Cleanup setup.py (#34) - this is actually quite important to improve the usage of the library

Possibly also merge this other PR:
* [ ] Support create / activate paradigm for pcap objects, and RFMON (#32)

Then:

* [x] Tag a new release and push tag to master
* [x] Upload release to pypi

@brifordwylie what you do think?

**Comment by hellais** [comment]
Done
